name: GitSync
main: me.vrganj.gitsync.GitSync
version: 1.2
api-version: 1.18

commands:
  gitsync:
    description: Sync the Git repository.

permissions:
  gitsync.*:
    children:
      gitsync.sync:
        default: op
        description: Allows for syncing the repository.
      gitsync.reload:
        default: op
        description: Allows for reloading the configuration.
